# Basic site settings
baseURL = "/"
title = "SOS Montpellier Ukraine"

# Language settings
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
languageCode = "fr-fr"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"

# Enable goldmark for markdown rendering
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allows HTML in markdown content
  
# Media handling
[imaging]
  anchor = "Smart"
  bgColor = "#ffffff"
  hint = "photo"
  quality = 85
  resampleFilter = "Lanczos"

# Output settings
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

# Language configuration
[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1
    title = "SOS Montpellier Ukraine"
    [languages.fr.params]
      description = "Association humanitaire SOS Montpellier Ukraine"