backend:
  name: git-gateway
  branch: main
  repo: M-D-Q/hugo-charity-website
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

site_url: https://sos-montpellier-ukraine.netlify.app
display_url: https://sos-montpellier-ukraine.netlify.app
logo_url: /images/logo.jpg

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow
locale: 'fr'


collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "posts/{{year}}/{{month}}/{{slug}}"
    format: "toml-frontmatter"
    extension: "md"
    frontmatter_delimiter: "+++"
    fields:
      - {label: "Titre", name: "title", widget: "string", hint: "Le titre de votre article"}
      - {label: "Date de publication", name: "date", widget: "datetime", hint: "Date et heure de publication"}
      - {label: "Brouillon", name: "draft", widget: "boolean", default: false}
      - {label: "Image principale", name: "image", widget: "image", hint: "L'image principale de votre article"}
      - {
          label: "Catégorie", 
          name: "category", 
          widget: "select", 
          options: [
            {label: "Mission médicale", value: "medical"},
            {label: "Distribution de vêtements", value: "clothing"},
            {label: "Aide alimentaire", value: "food"},
            {label: "Urgence", value: "urgent"},
            {label: "Actualité", value: "news"},
            {label: "Événement", value: "event"},
            {label: "Partenariat", value: "partnership"}
          ],
          hint: "Sélectionnez une catégorie"
        }
      - {
          label: "Tags", 
          name: "tags", 
          widget: "list", 
          allow_add: true, 
          default: ["actualité"],
          hint: "Ajoutez des tags pour mieux organiser vos articles"
        }
      - {
          label: "Numéro de mission", 
          name: "mission_number", 
          widget: "number", 
          required: false, 
          hint: "Optionnel - Le numéro de la mission si applicable"
        }
      - {
          label: "Lieu", 
          name: "location", 
          widget: "string", 
          required: false, 
          hint: "Optionnel - Le lieu concerné par l'article"
        }
      - {
          label: "Date de l'événement", 
          name: "event_date", 
          widget: "string", 
          required: false, 
          hint: "Optionnel - La date de l'événement si différente de la date de publication"
        }
      - label: "Alerte"
        name: "alert"
        widget: "object"
        required: false
        hint: "Optionnel - Ajoutez une alerte en haut de l'article"
        fields:
          - {
              label: "Type", 
              name: "type", 
              widget: "select", 
              options: ["success", "info", "warning"],
              required: false
            }
          - {
              label: "Message", 
              name: "message", 
              widget: "text",
              required: false
            }
      - label: "Appel à l'action"
        name: "cta"
        widget: "object"
        required: false
        hint: "Optionnel - Ajoutez un appel à l'action"
        fields:
          - {
              label: "Titre", 
              name: "title", 
              widget: "string",
              required: false
            }
          - {
              label: "Description", 
              name: "description", 
              widget: "text",
              required: false
            }
          - {
              label: "URL", 
              name: "url", 
              widget: "string",
              required: false
            }
          - {
              label: "Texte du bouton", 
              name: "button_text", 
              widget: "string",
              required: false
            }
      - {
          label: "Contenu", 
          name: "body", 
          widget: "markdown", 
          hint: "Le contenu principal de votre article",
          buttons: [
            "bold", 
            "italic", 
            "link", 
            "quote", 
            "bulleted-list", 
            "numbered-list",
            "heading-two",
            "heading-three"
          ],
          editor_components: ["image"]
        }